name: view_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - moviepy  # only available on conda-forge
  - openpyxl
  - jupyter
  - appdirs
