name: view_dev_py37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jinja2
  - easygui  # only available in conda-forge
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - moviepy  # only available on conda-forge
  - openpyxl
  - ipdb
  - nose
  - ipython
  - jupyter
  - appdirs
